/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-03 09:18:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class memberJoinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/member/../common/menubar.jsp", Long.valueOf(1574285738000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.outer {\r\n");
      out.write("\t\twidth:600px;\r\n");
      out.write("\t\theight:500px;\r\n");
      out.write("\t\tbackground:black;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tmargin-left:auto;\r\n");
      out.write("\t\tmargin-right:auto;\r\n");
      out.write("\t\tmargin-top:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#joinForm table {\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\tmargin:auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#joinForm td {\r\n");
      out.write("\t\ttext-align:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tinput {\r\n");
      out.write("\t\tmargin-top:2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tbutton {\r\n");
      out.write("\t\theight:22px;\r\n");
      out.write("\t\twidth:80px;\r\n");
      out.write("\t\tbackground:yellowgreen;\r\n");
      out.write("\t\tborder:yellowgreen;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tborder-radius:5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tbutton:hover {\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#idCheck, #pwdResult {\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#pwdResult {\r\n");
      out.write("\t\ttext-align:left;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 페이지를 이동해도 menubar는 계속 상단에 노출되도록 하자 -->\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');

	// 2_1_1. session 객체에 담겨진 loginUser 정보를 변수에 담는다
	Member loginUser = (Member)session.getAttribute("loginUser");

	// 회원 가입 성공 메세지 출력용
	String msg = (String)session.getAttribute("msg");
	
	String contextPath = request.getContextPath();


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar msg = \"");
      out.print( msg );
      out.write("\";\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tif(msg != \"null\"){\r\n");
      out.write("\t\t\talert(msg);\r\n");
      out.write("\t\t\t");
 session.removeAttribute("msg"); 
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tbackground: url('");
      out.print( request.getContextPath() );
      out.write("/resources/images/city1.PNG') no-repeat;\r\n");
      out.write("\t\tbackground-size : cover;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.loginArea > form, #userInfo {\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#memberJoinBtn, #loginBtn, #myPage, #logoutBtn {\r\n");
      out.write("\t\twidth:110px;\r\n");
      out.write("\t\theight:25px;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tborder-radius:5px;\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#memberJoinBtn, #myPage {\r\n");
      out.write("\t\tbackground:yellowgreen;\r\n");
      out.write("\t\tborder:yellowgreen;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#loginBtn, #logoutBtn {\r\n");
      out.write("\t\tbackground:orangered;\r\n");
      out.write("\t\tborder:orangered;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#memberJoinBtn:hover, #loginBtn:hover, #myPage:hover, #logoutBtn:hover {\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.wrap {\r\n");
      out.write("\t\tbackground:black;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.nav {\r\n");
      out.write("\t\twidth:600px;\r\n");
      out.write("\t\tmargin:auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menu {\r\n");
      out.write("\t\tbackground:black;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tvertical-align:middle;\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\theight:50px;\r\n");
      out.write("\t\tdisplay:table-cell;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menu:hover {\r\n");
      out.write("\t\tbackground:darkgray;\r\n");
      out.write("\t\tcolor:orangered;\r\n");
      out.write("\t\tfont-weight:bold;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1 align=\"center\">Welcome to JSP World!!</h1>\r\n");
      out.write("\t<div class=\"loginArea\">\r\n");
      out.write("\t<!-- 2_1. 로그인이 안 되어있는 경우와 되어 있는 경우가 다르게 보여야 하므로 if문 추가 -->\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("\t\t<!-- 1_1. 로그인 관련 폼 만들기 -->\r\n");
      out.write("\t\t<form id=\"loginForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/login.me\" method=\"post\" onsubmit=\"return validate();\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><label>ID : </label></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"userId\" id=\"userId\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><label>PWD : </label></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"userPwd\" id=\"userPwd\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\t\t\t<!-- form 태그 안에 있는 버튼의 디폴트 type은 submit이므로 다른 동작을 하고 싶을 때는 type=\"button\" 반드시 표시 -->\r\n");
      out.write("\t\t\t\t<button id=\"memberJoinBtn\" onclick=\"memberJoin();\" type=\"button\">회원가입</button>\r\n");
      out.write("\t\t\t\t<button id=\"loginBtn\" type=\"submit\">로그인</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t\t<!-- 로그인이 성공적으로 됐을 경우 -->\r\n");
      out.write("\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t<div id=\"userInfo\">\r\n");
      out.write("\t\t\t<label>");
      out.print( loginUser.getUserName() );
      out.write("님의 방문을 환영합니다.</label>\r\n");
      out.write("\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\t\t\t\t<button id=\"myPage\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/views/member/myPage.jsp';\">정보수정</button>\r\n");
      out.write("\t\t\t\t<button id=\"logoutBtn\" onclick=\"logout();\">로그아웃</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// 1_2. validate() 작성\r\n");
      out.write("\t\tfunction validate(){\r\n");
      out.write("\t\t\tif($(\"#userId\").val().trim().length == 0){\r\n");
      out.write("\t\t\t\talert('아이디를 입력하세요');\r\n");
      out.write("\t\t\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"#userPwd\").val().trim().length == 0){\r\n");
      out.write("\t\t\t\talert('비밀번호를 입력하세요');\r\n");
      out.write("\t\t\t\t$(\"#userPwd\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t\t// 여기까지 작성했으면 LoginServlet 만들러 가기~~~~\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 2_3. logout() 작성하기\r\n");
      out.write("\t\tfunction logout(){\r\n");
      out.write("\t\t\tlocation.href = '");
      out.print( request.getContextPath() );
      out.write("/logout.me';\r\n");
      out.write("\t\t\t// logout 버튼을 눌렀을 경우 logout.me url과 매핑되는 servlet으로 이동하여\r\n");
      out.write("\t\t\t// logout 처리 진행\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 3. 회원가입 버튼을 눌렀을 경우 회원 가입 페이지로 이동하는 memberJoin() 함수 작성\r\n");
      out.write("\t\tfunction memberJoin(){\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.print(request.getContextPath() );
      out.write("/views/member/memberJoinForm.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<br clear=\"both\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t<div class=\"nav\">\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"goMain();\">HOME</div>\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"goNotice();\">공지사항</div>\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"goBoard();\">게시판</div>\r\n");
      out.write("\t\t\t<div class=\"menu\" onclick=\"goThumbnail();\">사진게시판</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction goMain(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 1. 공지사항\r\n");
      out.write("\t\tfunction goNotice(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/list.no\";\r\n");
      out.write("\t\t\t// NoticeListServlet 만들기~~\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 2. 게시판\r\n");
      out.write("\t\tfunction goBoard(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( contextPath );
      out.write("/list.bo\";\r\n");
      out.write("\t\t\t// BoardListServlet 만들기~~\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 3. 사진 게시판\r\n");
      out.write("\t\tfunction goThumbnail(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( contextPath );
      out.write("/list.th\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 1. 회원 가입 -->\r\n");
      out.write("\t<!-- 1_1. 회원가입 폼 작성 -->\r\n");
      out.write("\t<div class=\"outer\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<h2 align=\"center\">회원가입</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form id=\"joinForm\" name=\"joinForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/insert.me\" method=\"post\" onsubmit=\"return joinValidate();\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"200px\">* 아이디</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" maxlength=\"13\" name=\"userId\" required></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"200px\">\r\n");
      out.write("\t\t\t\t\t\t<!-- ajax를 이용한 중복 확인 : onclick 지우고 실행 -->\r\n");
      out.write("\t\t\t\t\t\t<!-- <button id=\"idCheck\" type=\"button\" onclick=\"checkId()\">중복확인</button> -->\r\n");
      out.write("\t\t\t\t\t\t<button id=\"idCheck\" type=\"button\">중복확인</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>* 비밀번호</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" maxlength=\"15\" name=\"userPwd\" required></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>* 비밀번호 확인</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" maxlength=\"15\" name=\"userPwd2\" required></td>\r\n");
      out.write("\t\t\t\t\t<td><label id=\"pwdResult\"></label></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>* 이름</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" maxlength=\"5\" name=\"userName\" required></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>연락처</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"tel\" maxlength=\"11\" name=\"phone\" placeholder=\"(-없이)01012345678\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>이메일</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"email\" name=\"email\"></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>관심분야</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" id=\"sports\" name=\"interest\" value=\"운동\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"sports\">운동</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" id=\"climbing\" name=\"interest\" value=\"등산\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"climbing\">등산</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" id=\"fishing\" name=\"interest\" value=\"낚시\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"fishing\">낚시</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" id=\"cooking\" name=\"interest\" value=\"요리\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"cooking\">요리</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" id=\"game\" name=\"interest\" value=\"게임\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"game\">게임</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" id=\"etc\" name=\"interest\" value=\"기타\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"etc\">기타</label>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\t\t\t\t<button id=\"toMain\" onclick=\"returnToMain()\" type=\"button\">메인으로</button>\r\n");
      out.write("\t\t\t\t<!-- 아이디 중복확인이 되었을 경우에만 '가입하기' 버튼 활성화 하기 -->\r\n");
      out.write("\t\t\t\t<!-- <button id=\"joinBtn\">가입하기</button> -->\r\n");
      out.write("\t\t\t\t<button id=\"joinBtn\" disabled>가입하기</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 1. 메인으로 돌아가기\r\n");
      out.write("\t\tfunction returnToMain(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t// 2. 유효성 검사\r\n");
      out.write("\t\tfunction joinValidate(){\r\n");
      out.write("\t\t\tif(!(/^[a-z][a-z\\d]{3,11}$/.test($(\"#joinForm input[name=userId]\").val()))){\r\n");
      out.write("\t\t\t\talert('아이디는 영소문자로 시작해서 4~12자 입력(숫자 포함 가능)');\r\n");
      out.write("\t\t\t\t$(\"#joinForm input[name=userId]\").select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(\"#joinForm input[name=userPwd]\").val() != $(\"#joinForm input[name=userPwd2]\").val()){\r\n");
      out.write("\t\t\t\t$(\"#pwdResult\").text(\"비밀번호 불일치\").css(\"color\",\"red\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(!(/^[가-힣]{2,}$/.test($(\"#joinForm input[name=userName]\").val()))){\r\n");
      out.write("\t\t\t\talert('이름은 한글로 2글자 이상 입력');\r\n");
      out.write("\t\t\t\t$(\"#joinForm input[name=userName]\").select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t// 3. 회원 가입\r\n");
      out.write("\t\t// InsertMemberServlet 만들어서 진행\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 4. 아이디 중복체크\r\n");
      out.write("\t\tfunction checkId(){\r\n");
      out.write("\t\t\twindow.open(\"idCheckForm.jsp\", \"checkForm\", \"width=300, height=200\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// ---------------------------------------------------------------------------\r\n");
      out.write("\t\t// ajax를 이용한 id 중복 확인\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tvar isUsable = false;\r\n");
      out.write("\t\t\t// 아이디 중복시 false, 아이디 사용 가능시 true -> 나중에 유효성 검사\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#idCheck\").click(function() {\r\n");
      out.write("\t\t\t\tvar userId = $(\"#joinForm input[name='userId']\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(!userId || userId.val().length < 4) {\r\n");
      out.write("\t\t\t\t\talert(\"아이디는 최소 4자리 이상이어야 합니다.\");\r\n");
      out.write("\t\t\t\t\tuserId.focus();\r\n");
      out.write("\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t// ajax로 중복여부 확인\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"");
      out.print( request.getContextPath() );
      out.write("/idCheck.me\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\tdata : {userId:userId.val()},\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\tif(data == \"fail\") { // script에서는 equals로 안쓰는듯\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"사용할 수 없는 아이디입니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\tuserId.focus();\r\n");
      out.write("\t\t\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\t\t\tif(confirm(\"사용 가능한 아이디입니다. 사용하시겠습니까?\")) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tuserId.prop('readonly', true); // 더이상 userId에 값 입력해서 변경할 수 없도록\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// prop : 속성 중 true/false 값을 갖고있는 속성\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// css : 스타일\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// attr : 속성\r\n");
      out.write("\t\t\t\t\t\t\t\t\tisUsable = true;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// -> 사용 가능하다는 flag값\r\n");
      out.write("\t\t\t\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tuserId.focus();\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(isUsable) {\r\n");
      out.write("\t\t\t\t\t\t\t\t// 아이디 중복 체크 후 사용 가능한 아이디이며 사용하기로 한 경우\r\n");
      out.write("\t\t\t\t\t\t\t\t// 회원가입 버튼 활성화\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#joinBtn\").removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log('서버 통신 안됨');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
