/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-03 11:44:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\t<h1 align=\"center\">JavaScript를 이용한 Ajax 테스트</h1>\r\n");
      out.write("\t<h3>1. 버튼 클릭시 Get방식으로 서버에 데이터 전송 및 응답</h3>\r\n");
      out.write("\t<button onclick=\"jsAjax1();\">Get방식 전송</button>\r\n");
      out.write("\t<p id=\"test1\"></p>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction jsAjax1() {\r\n");
      out.write("\t\t\t// 1. XMLHttpRequest 객체 생성\r\n");
      out.write("\t\t\txhr = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 자바스크립트는 원래 브라우저 버젼벌 호환성 검사가 필요하지만 생략~\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 2. onreadystatechange : Ajax 통신에 대한 응답 상태의 변경이 있을 경우\r\n");
      out.write("\t\t\t// 실행할 함수(Ajax 통신이 성공한 경우에 대한 동작)\r\n");
      out.write("\t\t\txhr.onreadystatechange = function() {\r\n");
      out.write("\t\t\t\t// 1) readyState : 서버 응답 상태 확인(Ajax 통신 진행상황 확인)\r\n");
      out.write("\t\t\t\t/* \r\n");
      out.write("\t\t\t\t\t0 : request not initialized\r\n");
      out.write("\t\t\t\t\t1 : server connection established\r\n");
      out.write("\t\t\t\t\t2 : request received\r\n");
      out.write("\t\t\t\t\t3 : processing request\r\n");
      out.write("\t\t\t\t\t4 : request finished and response is ready\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\tif(xhr.readyState == 4) {\r\n");
      out.write("\t\t\t\t\t// 요청이 끝났고 그에 해당하는 응답이 왔을 경우\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 2) status : HTTP 응답 상태 코드(응답이 정상적으로 이루어졌는지 확인)\r\n");
      out.write("\t\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\t\t200 : \"OK\"\r\n");
      out.write("\t\t\t\t\t\t403 : \"Forbidden\"\r\n");
      out.write("\t\t\t\t\t\t404 : \"Not Found\"\r\n");
      out.write("\t\t\t\t\t*/\r\n");
      out.write("\t\t\t\t\tif(xhr.status == 200) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log('jsAjax1() - ajax 통신 성공!');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t// xhr.responseText : 응답 데이터 문자열을 담고 있다.\r\n");
      out.write("\t\t\t\t\t\tvar str = xhr.responseText;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"test1\").innerHTML = str;\r\n");
      out.write("\t\t\t\t\t}else if(xhr.status == 404) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log('jsAjax1() - ajax 통신 실패!');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// 3. open() : 서버와 데이터 교환시 필요한 정보 입력(요청 방식, 대상(서버), 동기/비동기)\r\n");
      out.write("\t\t\txhr.open(\"GET\", \"");
      out.print(request.getContextPath());
      out.write("/jsAjax1.do?name=홍길동&age=20\", true);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 4. send() : 서버로 데이터 교환 요청\r\n");
      out.write("\t\t\txhr.send();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<h3>2. 버튼 클릭 시 POST 방식으로 서버에 데이터 전송 및 응답</h3>\r\n");
      out.write("\t<button onclick=\"jsAjax2();\">POST방식 전송</button>\r\n");
      out.write("\t<p id=\"test2\"></p>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction jsAjax2() {\r\n");
      out.write("\t\t\t// 1 XMLHttpRequest 객체 생성\r\n");
      out.write("\t\t\txhr = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 2. onreadystatechange\r\n");
      out.write("\t\t\txhr.onreadystatechange = function() {\r\n");
      out.write("\t\t\t\tif(xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"jsAjax2() - ajax 통신 성공!\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar str = xhr.responseText;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"test2\").innerHTML = str;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 3. open() : 서버와 데이터 교환 시 필요한 정보 입력\r\n");
      out.write("\t\t\txhr.open(\"POST\", \"");
      out.print(request.getContextPath());
      out.write("\r\n");
      out.write("\t\t/jsAjax2.do\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t// **** POST 방식 데이터 전송시 send() 호출 전 mime type을 설정해주어야 함 ****\r\n");
      out.write("\t\t\t// POST 전송 시 header에 추가로 설정하지 않으면 전송한 파라미터를 인식하지 못함\r\n");
      out.write("\t\t\t// key=value&key=value&...\r\n");
      out.write("\t\t\txhr.setRequestHeader(\"Content-type\",\r\n");
      out.write("\t\t\t\t\t\"application/x-www-form-urlencoded;\");\r\n");
      out.write("\t\t\t// HTTP요청 헤더의 값을 설정. setRequestHeader(header(설정된값을 가진 헤더이름), value(헤더의 본문에 설정될 값))\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 4. send()\r\n");
      out.write("\t\t\txhr.send(\"name=김말똥&age=30\"); // send 시 데이터 전송\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<h1 align=\"center\">jQuery를 이용한 Ajax 테스트</h1>\r\n");
      out.write("\t<h3>1. 버튼 클릭시 GET 방식으로 서버에 데이터 전송 및 응답</h3>\r\n");
      out.write("\t입력 :\r\n");
      out.write("\t<input type=\"text\" id=\"input1\">\r\n");
      out.write("\t<button id=\"btn1\">전송</button>\r\n");
      out.write("\t응답 :\r\n");
      out.write("\t<input type=\"text\" id=\"output1\" style=\"width: 300px\" readonly>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t// 1. 버튼 클릭시 GET 방식으로 서버에 입력값 전송 및 응답\r\n");
      out.write("\t\t\t$(\"#btn1\").click(function() {\r\n");
      out.write("\t\t\t\tvar input = $(\"#input1\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t// url : 데이터를 전송할 url(필수!!)\r\n");
      out.write("\t\t\t\t\turl : \"jqAjax1.do\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// data : 요청 시 전달할 파라미터 설정\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tinput : input\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t// key:value\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// type : 전송방식(GET/POST)\r\n");
      out.write("\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// success : Ajax 통신 성공 시 처리할 함수를 지정하는 속성\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t// result 매개변수 : 서버에서 응답이 왔을 때 그 값이 저장되는 변수\r\n");
      out.write("\t\t\t\t\t\t// 매개변수명 임의지정 가능\r\n");
      out.write("\t\t\t\t\t\tconsole.log('Ajax 통신 성공!');\r\n");
      out.write("\t\t\t\t\t\t$(\"#output1\").val(result);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// error : Ajax 통신 실패 시 처리할 함수를 지정하는 속성\r\n");
      out.write("\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\tconsole.log('Ajax 통신 실패...');\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// complete : 통신 성공/실패 여부 상관없ㅇ ㅣ실행\r\n");
      out.write("\t\t\t\t\tcomplete : function() {\r\n");
      out.write("\t\t\t\t\t\tconsole.log('무조건 호출~!');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<h3>2. 버튼 클릭시 POST 방식으로 서버에 데이터 전송 및 응답</h3>\r\n");
      out.write("\t입력 :\r\n");
      out.write("\t<input type=\"text\" id=\"input2\">\r\n");
      out.write("\t<button id=\"btn2\">전송</button>\r\n");
      out.write("\t응답 :\r\n");
      out.write("\t<input type=\"text\" id=\"output2\" style=\"width: 300px\" readonly>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#btn2\").click(function() {\r\n");
      out.write("\t\t\t\tvar input = $(\"#input2\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"jqAjax2.do\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tinput : input\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"Ajax 통신 성공!\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#output2\").val(result);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tcomplete : function() {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"무조건 호출\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<h3>3. 버튼 클릭시 POST 방식으로 서버에 여러개의 데이터 전송 및 응답</h3>\r\n");
      out.write("\t이름 :\r\n");
      out.write("\t<input type=\"text\" id=\"input3_1\"> 나이 :\r\n");
      out.write("\t<input type=\"text\" id=\"input3_2\">\r\n");
      out.write("\t<button id=\"btn3\">전송</button>\r\n");
      out.write("\t응답 :\r\n");
      out.write("\t<input type=\"text\" id=\"output3\" style=\"width: 300px\" readonly>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#btn3\").click(function() {\r\n");
      out.write("\t\t\t\tvar input3_1 = $(\"#input3_1\").val();\r\n");
      out.write("\t\t\t\tvar input3_2 = $(\"#input3_2\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"jqAjax3.do\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tname : input3_1,\r\n");
      out.write("\t\t\t\t\t\tage : input3_2\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#output3\").val(result);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#output3\").val(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<h3>4. 서버로 기본형 데이터 전송 후, 응답을 객체(Object)로 받기</h3>\r\n");
      out.write("\t<h4>번호를 입력하여 조회하고자 하는 사용자 정보를 요청, 사용자가 없는 경우 \"사용자 정보가 없습니다.\" 출력</h4>\r\n");
      out.write("\r\n");
      out.write("\t회원정보 입력 :\r\n");
      out.write("\t<input type=\"text\" id=\"input4\">\r\n");
      out.write("\t<button id=\"btn4\">조회</button>\r\n");
      out.write("\t<textarea id=\"textarea4\" rows=\"4\" cols=\"30\"></textarea>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t// JSONObject를 서버로부터 전달받아\r\n");
      out.write("\t\t\t// dataType : \"json\"을 이용하여 처리\r\n");
      out.write("\t\t\t$(\"#btn4\").click(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar input = $(\"#input4\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : \"jqAjax4.do\",\r\n");
      out.write("\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\tinput : input\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\t\t\tdataType : \"json\", // 응답 데이터의 형식을 text가 아닌 json으로 지정\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(obj) {\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(obj);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar result = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tif (obj != null) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresult = \"번호 : \" + obj.no + \"\\n\" + \"이름 : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ obj.name + \"\\n\" + \"나이 : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ obj.age + \"\\n\" + \"성별 : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ obj.gender;\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresult = \"사용자 정보가 없습니다.\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#textarea4\").val(result);\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#textarea4\").val(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<h3>5. 서버로 기본형 데이터를 전송 후, 응답을 리스트(List) 형태로 받기</h3>\r\n");
      out.write("\t<h4>선택한 성별을 가진 모든 회원 정보 가져오기</h4>\r\n");
      out.write("\t성별 : 남\r\n");
      out.write("\t<input type=\"radio\" name=\"chk_gender5\" value=\"남\" checked> 여\r\n");
      out.write("\t<input type=\"radio\" name=\"chk_gender5\" value=\"여\">\r\n");
      out.write("\t<button id=\"btn5\">조회</button>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<textarea id=\"textarea5\" rows=\"5\" cols=\"30\"></textarea>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#btn5\").click(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar gen = $(\"input[name='chk_gender5']:checked\").val();\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : \"jqAjax5.do\",\r\n");
      out.write("\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\tgender : gen\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(list) {\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(list);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t// $.each(배열명, function(index){});\r\n");
      out.write("\t\t\t\t\t\t\t\t// --> 배열명[index] 각 요소에 접근 가능\r\n");
      out.write("\t\t\t\t\t\t\t\tvar result = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t$.each(list, function(i) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresult += list[i].no + \" / \" + list[i].name\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ \" / \" + list[i].age + \" / \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ list[i].gender + \"\\n\";\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#textarea5\").val(result);\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<h3>6. 서버로 데이터 전송 후, 응답을 맵(Map) 형태로 받아서 테이블에 출력하기</h3>\r\n");
      out.write("\t<h4>조회하고자 하는 회원의 이름 키워드를 입력해서 조회되는 회원들 정보와 전달된 키워드를 받아오기</h4>\r\n");
      out.write("\t이름 :\r\n");
      out.write("\t<input type=\"text\" id=\"input6\" width=\"300\">\r\n");
      out.write("\t<button id=\"btn6\">검색</button>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<table id=\"memberTable6\" border=\"1\" style=\"text-align: center\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t<th>나이</th>\r\n");
      out.write("\t\t\t\t<th>성별</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#btn6\").click(function() {\r\n");
      out.write("\t\t\t\tvar input = $(\"#input6\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"jqAjax6.do\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tkeyword : input\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(map) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(map);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tconsole.log(map[\"jArr\"]);\r\n");
      out.write("\t\t\t\t\t\tconsole.log(map[\"keyword\"]);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar $tableBody = $(\"#memberTable6 tbody\");\r\n");
      out.write("\t\t\t\t\t\t// var tableBody로 변수를 선언하지 않고 $tableBody로\r\n");
      out.write("\t\t\t\t\t\t// 변수를 선언하는 이유는?\r\n");
      out.write("\t\t\t\t\t\t// tableBody --> 자바스크립트 변수, 스크립트만 사용 가능\r\n");
      out.write("\t\t\t\t\t\t// $tableBody --> jQuery 변수, jQuery에서 사용하는 내장함수들 모두 사용 가능\r\n");
      out.write("\t\t\t\t\t\t// 따라서 그냥 $를 첫글자에 써서 그것이 jQuery의 확장 객체임을 쉽게 구별하려는 의도로 통상 사용\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$tableBody.html(\"\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$.each(map[\"jArr\"], function(index, value) {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(value);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar $tr = $(\"<tr>\");\r\n");
      out.write("\t\t\t\t\t\t\tvar $noTd = $(\"<td>\").text(value.no); // <td>1</td>\r\n");
      out.write("\t\t\t\t\t\t\tvar $nameTd = $(\"<td>\").text(value.name); // <td>김영희</td>\r\n");
      out.write("\t\t\t\t\t\t\tvar $ageTd = $(\"<td>\").text(value.age); // <td>30</td>\r\n");
      out.write("\t\t\t\t\t\t\tvar $genTd = $(\"<td>\").text(value.gender); // <td>여</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$tr.append($noTd);\r\n");
      out.write("\t\t\t\t\t\t\t$tr.append($nameTd);\r\n");
      out.write("\t\t\t\t\t\t\t$tr.append($ageTd);\r\n");
      out.write("\t\t\t\t\t\t\t$tr.append($genTd);\r\n");
      out.write("\t\t\t\t\t\t\t// <tr> 사이에 위의 <td> 요소들이 모두 들어간다.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$tableBody.append($tr);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\tconsole.log('ajax 통신 실패!');\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<h3>7. Gson을 이용한 List 반환</h3>\r\n");
      out.write("\t<button id=\"gsonListBtn\">list 가져오기</button>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<textarea id=\"textarea7\" rows=\"10\" cols=\"30\"></textarea>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#gsonListBtn\").click(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : \"jqAjax7.do\",\r\n");
      out.write("\t\t\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(list) {\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(list);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar result = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t$.each(list, function(index, value) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresult += value.no + \" / \" + value.name\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ \" / \" + value.age + \" / \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ value.gender + \"\\n\"\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#textarea7\").val(result);\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"ajax 통신 실패!\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<h3>8. 연습</h3>\r\n");
      out.write("\t<h4>번호를 입력하여 조회하고자 하는 사용자 정보를 요청, 해당 결과를 테이블에 누적시킨다. 없는 번호를 입력했을 시\r\n");
      out.write("\t\t에러나지 않도록 처리할 것.</h4>\r\n");
      out.write("\t회원번호 입력 :\r\n");
      out.write("\t<input type=\"text\" id=\"input8\">\r\n");
      out.write("\t<button id=\"btn8\">조회</button>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<table id=\"memberTable8\" border=\"1\" style=\"text-align: center\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t<th>나이</th>\r\n");
      out.write("\t\t\t\t<th>성별</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#btn8\").click(function() {\r\n");
      out.write("\t\t\t\tvar input = $(\"#input8\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"jqAjax8.do\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tkeyword : input\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(user) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// var tableBody로 변수를 선언하지 않고 $tableBody로\r\n");
      out.write("\t\t\t\t\t\t// 변수를 선언하는 이유는?\r\n");
      out.write("\t\t\t\t\t\t// tableBody --> 자바스크립트 변수, 스크립트만 사용 가능\r\n");
      out.write("\t\t\t\t\t\t// $tableBody --> jQuery 변수, jQuery에서 사용하는 내장함수들 모두 사용 가능\r\n");
      out.write("\t\t\t\t\t\t// 따라서 그냥 $를 첫글자에 써서 그것이 jQuery의 확장 객체임을 쉽게 구별하려는 의도로 통상 사용\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$tableBody.html(\"\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif (user != null) {\r\n");
      out.write("\t\t\t\t\t\t\tvar $tableBody = $(\"#memberTable8 tbody\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar $tr = $(\"<tr>\");\r\n");
      out.write("\t\t\t\t\t\t\tvar $noTd = $(\"<td>\").text(user.no); // <td>1</td>\r\n");
      out.write("\t\t\t\t\t\t\tvar $nameTd = $(\"<td>\").text(user.name); // <td>김영희</td>\r\n");
      out.write("\t\t\t\t\t\t\tvar $ageTd = $(\"<td>\").text(user.age); // <td>30</td>\r\n");
      out.write("\t\t\t\t\t\t\tvar $genTd = $(\"<td>\").text(user.gender); // <td>여</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$tr.append($noTd);\r\n");
      out.write("\t\t\t\t\t\t\t$tr.append($nameTd);\r\n");
      out.write("\t\t\t\t\t\t\t$tr.append($ageTd);\r\n");
      out.write("\t\t\t\t\t\t\t$tr.append($genTd);\r\n");
      out.write("\t\t\t\t\t\t\t// <tr> 사이에 위의 <td> 요소들이 모두 들어간다.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$tableBody.append($tr);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\tconsole.log('ajax 통신 실패!');\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
