BEGIN 
    FOR I IN 1..105
    LOOP
        INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, 10, '제목' || I, '내용' || I, 
        2, DEFAULT, SYSDATE, SYSDATE, DEFAULT);
    END LOOP;
END;
/

COMMIT;

SELECT *
FROM(SELECT ROWNUM RNUM, A.*
    FROM (SELECT BID, BTYPE, CNAME, BTITLE, BCONTENT, USER_NAME, BCOUNT, CREATE_DATE,
           B.MODIFY_DATE, B.STATUS
    FROM BOARD B
    JOIN CATEGORY USING(CID)
    JOIN MEMBER ON(BWRITER=USER_NO)
    WHERE BTYPE = 1
    AND B.STATUS = 'Y'
    ORDER BY BID DESC) A)
WHERE RNUM BETWEEN 11 AND 20;

CREATE OR REPLACE VIEW BLIST
AS SELECT ROWNUM RNUM, A.*
    FROM (SELECT BID, BTYPE, CNAME, BTITLE, BCONTENT, USER_NAME, BCOUNT, CREATE_DATE,
           B.MODIFY_DATE, B.STATUS
    FROM BOARD B
    JOIN CATEGORY USING(CID)
    JOIN MEMBER ON(BWRITER=USER_NO)
    WHERE BTYPE = 1
    AND B.STATUS = 'Y'
    ORDER BY BID DESC) A;
    
    SELECT BID, BTYPE, CNAME, BTITLE, BCONTENT, BWRITER, USER_NAME, BCOUNT,
           CREATE_DATE, B.MODIFY_DATE, B.STATUS
    FROM BOARD B
    JOIN MEMBER M ON(B.BWRITER = M.USER_NO)
    JOIN CATEGORY C ON(B.CID = C.CID)
    WHERE B.STATUS = 'Y' AND BID=105;
    
    CREATE OR REPLACE VIEW BDETAIL
    AS SELECT BID, BTYPE, CNAME, BTITLE, BCONTENT, BWRITER, USER_NAME, BCOUNT,
           CREATE_DATE, B.MODIFY_DATE, B.STATUS
    FROM BOARD B
    JOIN MEMBER M ON(B.BWRITER = M.USER_NO)
    JOIN CATEGORY C ON(B.CID = C.CID)
    WHERE B.STATUS = 'Y';
    
    
    














