-- ´ñ±Û µî·Ï
INSERT INTO REPLY
VALUES(SEQ_RID.NEXTVAL, '´ñ±Û3', 203, 62, SYSDATE, SYSDATE, DEFAULT);
COMMIT;
-- ´ñ±Û SELECT
SELECT RID, RCONTENT, REF_BID, USER_NAME, R.CREATE_DATE, R.MODIFY_DATE, R.STATUS
FROM REPLY R
JOIN MEMBER M ON(R.RWRITER = M.USER_NO)
WHERE R.STATUS = 'Y'
AND REF_BID = 203
ORDER BY RID DESC;
-- VIEW·Î ¸¸µé±â
CREATE OR REPLACE VIEW RLIST
AS SELECT RID, RCONTENT, REF_BID, USER_NAME, R.CREATE_DATE, R.MODIFY_DATE, R.STATUS
FROM REPLY R
JOIN MEMBER M ON(R.RWRITER = M.USER_NO)
WHERE R.STATUS = 'Y'
ORDER BY RID DESC;

-- VIEW SELECT
SELECT * FROM RLIST WHERE REF_BID = 203;
