-- 샘플 데이터 입력(BOARD)
INSERT INTO BOARD
VALUES(SEQ_BID.NEXTVAL, 2, 10, '사진제목', '사진내용', 2,
       DEFAULT, SYSDATE, SYSDATE, DEFAULT);
-- 샘플 데이터 입력(ATTACHMENT)
INSERT INTO ATTACHMENT
VALUES(SEQ_FID.NEXTVAL, SEQ_BID.CURRVAL, 'origin.png', 'change.png',
'저장경로', SYSDATE, 0, DEFAULT, DEFAULT);

COMMIT;

-- selectBList
SELECT BID, BTYPE, CNAME, BTITLE, BCONTENT, USER_NAME, BCOUNT, 
       CREATE_DATE, B.MODIFY_DATE, B.STATUS
FROM BOARD B
JOIN CATEGORY USING(CID)
JOIN MEMBER ON(BWRITER = USER_NO)
WHERE BTYPE=2 AND B.STATUS='Y'
ORDER BY BID DESC;

-- selectFList
SELECT *
FROM ATTACHMENT
WHERE STATUS='Y'
AND FILE_LEVEL = 0;










